const data = {
    products:[
        {
            _id: '1',
            name: 'Lays Maxx: Macho Chilli',
            category: 'Snacks',
            image: '/resources/lays-maxx.jpeg',
            price: 60,
            brand: 'Lays',
            rating: 4,
            numReviews: 50,
            description: 'Lays Maxx: Macho Chilli',
        },
        {
            _id: '2',
            name: 'Daawat Brown Rice',
            category: 'Grain',
            image: '/resources/brown-rice.jpg',
            price: 100,
            brand: 'Daawat',
            rating: 4.5,
            numReviews: 110,
            description: 'Daawat Brown Rice',
        },
        {
            _id: '3',
            name: 'Lays Maxx: Macho Chilli',
            category: 'Snacks',
            image: '/resources/lays-maxx.jpeg',
            price: 60,
            brand: 'Lays',
            rating: 4,
            numReviews: 50,
            description: 'Lays Maxx: Macho Chilli',
        },
        {
            _id: '4',
            name: 'Lays Maxx: Macho Chilli',
            category: 'Snacks',
            image: '/resources/lays-maxx.jpeg',
            price: 60,
            brand: 'Lays',
            rating: 4,
            numReviews: 50,
            description: 'Lays Maxx: Macho Chilli',
        },
        {
            _id: '5',
            name: 'Lays Maxx: Macho Chilli',
            category: 'Snacks',
            image: '/resources/lays-maxx.jpeg',
            price: 60,
            brand: 'Lays',
            rating: 4,
            numReviews: 50,
            description: 'Lays Maxx: Macho Chilli',
        },
        {
            _id: '6',
            name: 'Lays Maxx: Macho Chilli',
            category: 'Snacks',
            image: '/resources/lays-maxx.jpeg',
            price: 60,
            brand: 'Lays',
            rating: 4,
            numReviews: 50,
            description: 'Lays Maxx: Macho Chilli',
        },

    ],
};
export default data;